services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: messaging-springboot-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: messaging-springboot-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: messaging-springboot-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://messaging-springboot-kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:15-alpine
    container_name: messaging-springboot-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=messaging_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app-messaging:
    build: .  # No mundo Linux e Docker, o ponto (.) significa "Aqui mesmo, nesta pasta onde eu estou".
    container_name: app-java
    ports:
      - "8080:8080"          # Para vocÃª testar pelo Postman/Chrome
    depends_on:
      - kafka                # Espera o Kafka ligar
      - postgres             # Espera o Banco ligar
    environment:
      - KAFKA_HOST=messaging-springboot-kafka     # AQUI! Mandamos usar o nome interno
      - KAFKA_PORT=29092     # AQUI! Mandamos usar a porta interna
      - DB_HOST=messaging-springboot-postgres

volumes:
  postgres-data: