spring:
  application:
    name: messaging-springboot

  datasource:
    url: jdbc:postgresql://localhost:5432/messaging_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    # Diz pro Hibernate falar o "dialeto" correto do Postgres
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true # Mostra os comandos SQL no terminal (útil para aprender)

  kafka:
    consumer:
      group-id: group-1
      auto-offset-reset: earliest
      # O SEGREDO ESTÁ AQUI EMBAIXO:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
            json:
              trusted:
                packages: '*' # Importante: Confia em qualquer pacote para deserializar
    listener:
      ack-mode: RECORD
    producer:
          # Mudou de StringSerializer para JsonSerializer (pega o objeto Java e transforma em json para ser aceito pelo kafka)
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
